### ISSUE TITLE
Error when following the packing and recording simultaneously instructions

### ISSUE THREAD

**Issue by ikreymer** [reprozip-news-apps/reprozip-web#9]
Hi, nice working in creating this prototype!
I was trying to follow the instructions for doing the recording + packing option:

```
reprounzip dj live-record http://localhost:3000 /path/to/target
```

and this resulted in the following exception:

```
Traceback (most recent call last):
  File "/home/ubuntu/reprozip-web/py37/bin/reprounzip", line 11, in <module>
    load_entry_point('reprounzip==1.0.13', 'console_scripts', 'reprounzip')()
  File "/home/ubuntu/reprozip-web/py37/lib/python3.7/site-packages/reprounzip/main.py", line 144, in main
    args.func(args)
  File "/home/ubuntu/reprozip-web/py37/lib/python3.7/site-packages/reprozip_web-0.1-py3.7.egg/reprounzip/unpackers/dj.py", line 494, in live_record
    record(args)
  File "/home/ubuntu/reprozip-web/py37/lib/python3.7/site-packages/reprozip_web-0.1-py3.7.egg/reprounzip/unpackers/dj.py", line 452, in record
    WARCPacker.no_second_pass(args.pack[0])
AttributeError: 'Namespace' object has no attribute 'pack'
```

**Comment by quoideneuf** [comment]
Thanks @ikreymer - The commit above should fix this. It looks like something that just broke along the way, as the live-record feature isn't one we exercised very much.
